### ISSUE TITLE
Issue with new IMDb csv format

### ISSUE THREAD

**Issue by pfgb** [nilsgeilen/imdb-analysis#1]
Apparently, IMDb made some changes on its ratings files, which caused your (excellent, thank you very much for this tool) website to stop identifying the Title Types correctly, which, in turn, caused a snowball effect that effectively made your unable to do any sorts of analysis as it identified 0 elements. 

I've tried messing around with the csv and I think I found the root cause:
-the Title Type entries have been edited by IMDb, now what was called "movie" has become "Movie", "video" is "Video" and "tvMovie" is now "TV Movie". I strongly believe that editing your code to search for the new categories on this column will solve all the issues as editing the .csv to go back to the older categories works (at least for me).

Sorry to bother with such a small issue and it's a pretty easy solution from the user side, but I figured letting you know is a nice thing to do.

Thank you.

**Comment by nilsgeilen** [comment]
Thank you for making me aware ! The site should work with the new format now. The title types seem to be localised to the imdb user's configured language now, so I could not filter for films anymore and all items are included now (tv series, episodes, documentares). Otherwise I would have needed to account for all languages that imdb supports. I also changed the first table into a chart and I made items of different title types hideable in the runtime scatter chart, as some tv series items really change the scale to much. 

Another change in the new format is that the film titles are localised (finally I can tell those Park Chan Wook movies apart ^^). Also the release dates have changes, probably to the release dates for language version of the user's locale.
